name: K6 load test
on: [push]
permissions:
  contents: write
jobs:
  build: 
    name: K6 load test
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v4

      - name: step 2 - run k6 load test
        uses: grafana/run-k6-action@v1
        with: 
          filename: main/execucaoCloudGrafana.js